apiVersion: apps/v1
kind: Deployment
metadata: 
  name: flaskapp
  labels:
    app: flaskapp
    tier: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flaskapp
      tier: frontend
  template:
    metadata:
      labels:
        app: flaskapp
        tier: frontend
    spec:
      containers:
      - name: flaskapp
        env:
        - name: DB_PASSWORD
          value: root
        image: mehrshadlotfi/flaskapp:1.1.0
        ports:
        - containerPort: 8080
