apiVersion: v1
kind: Service
metadata: 
  name: flaskapp
  labels:
    app: flaskapp
    tier: frontend
spec:
  type: NodePort
  ports:
  - port: 5000
  selector:
    app: flaskapp
    tier: frontend
