apiVersion: v1
kind: Service
metadata: 
  name: flaskapp-mysql
  labels:
    app: flaskapp-mysql
    tier: backend
spec:
  type: ClusterIP
  ports:
  - port: 3306
    targetPort: 3306
  selector:
    app: flaskapp-mysql
    tier: backend
