version: "2"
services:
  app:
    build: 
      context: ./app
      dockerfile: app.Dockerfile
    links:
      - db
    ports:
      - "5000:5000"
  db:
    platform: linux/x86_64
    image: mysql:5.7
    ports:
      - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro
